### ISSUE TITLE
Fatal error: Class ‘Tribe__PUE__Package_Handler’ not found

### ISSUE THREAD

**Issue by lukecav** [moderntribe/tribe-common#247]
https://github.com/moderntribe/tribe-common/blob/9ac6020ea1ea89cad19249bb8d0c4990bba32602/src/Tribe/PUE/Checker.php#L200

**Comment by barryhughes** [comment]
Thanks for the report @lukecav and our apologies for the difficulties: this should actually now be resolved (it shouldn't have been an issue if you were pulling directly from our git repo, but we also pushed a 4.3.1.1 release over on wordpress.org).

I hope that helps!

**Comment by lukecav** [comment]
So the issue is resolved in the event calendar and event tickets then, since they use the common library?

**Comment by barryhughes** [comment]
Essentially, yes.

The problem was that due to an error on our side the Event Tickets release on wordpress.org was missing a number of files from tribe-common. So, if you downloaded Event Tickets 4.3.1 from wordpress.org (whether directly or by automatic update), you'd have hit this bug.

The corrective action was basically committing those missing files over on the corresponding wordpress.org svn repo - but after doing that we also 'bumped' the version number of Event Tickets.
